global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - lead-scanner-prometheus:9090

  - job_name: lead-scanner-monitor
    metrics_path: /metrics
    static_configs:
      - targets:
          - lead-scanner-monitor:8002

  - job_name: lead-scanner-bot
    metrics_path: /metrics
    static_configs:
      - targets:
          - lead-scanner-bot:8003
